# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Acceptance Tests
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
    paths:
      - '.github/workflows/acceptance-tests.yml'
      - 'tests/**'
      - '**.php'
      - 'codeception.dist.yml'
      - 'composer.json'
      - 'docker-compose.yml'
      - 'package.json'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/acceptance-tests.yml'
      - 'tests/**'
      - '**.php'
      - 'codeception.dist.yml'
      - 'composer.json'
      - 'docker-compose.yml'
      - 'package.json'
  workflow_dispatch:

jobs:
  test:
    name: WP ${{ matrix.wp }} / PHP ${{ matrix.php }}
    strategy:
      matrix:
        wp:
          - '6.4'
          - '6.3'
        php:
          - '8.2'
          - '7.4'
        include:
          - wp: '6.4'
            php: '8.3'
      fail-fast: false
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-acceptance-tests.yml@trunk
    with:
      wp: ${{ matrix.wp }}
      php: ${{ matrix.php }}
      node: false
