# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Acceptance Tests
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
      - 'master'
  pull_request:
    branches:
      - '**'
  schedule:
    # Once weekly on Mondays at 04:00 UTC.
    #
    #        ┌───────────── minute           (0 - 59)
    #        │  ┌────────── hour             (0 - 23)
    #        │  │  ┌─────── day of the month (1 - 31)
    #        │  │  │  ┌──── month            (1 - 12 or JAN-DEC)
    #        │  │  │  │  ┌─ day of the week  (0 - 6 or SUN-SAT)
    #        │  │  │  │  │
    #        │  │  │  │  │
    #        │  │  │  │  │
    - cron: '0  4  *  *  1'
  workflow_dispatch:

jobs:
  test:
    name: WP ${{ matrix.wp }} / PHP ${{ matrix.php }}
    strategy:
      matrix:
        wp:
          - 'nightly'
          - '6.4'
          - '6.3'
        php:
          - '8.2'
          - '8.1'
          - '8.0'
          - '7.4'
        dev:
          - ${{ github.ref_name == 'develop' }}
        exclude:
          # Only run the nightly tests on the develop branch.
          - wp: 'nightly'
            dev: false
      fail-fast: false
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-acceptance-tests.yml@trunk
    with:
      wp: ${{ matrix.wp }}
      php: ${{ matrix.php }}
      node: false
