# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Deploy Assets
on:
  push:
    branches:
      - deploy

permissions: {}

jobs:
  wordpress:
    name: WordPress.org
    permissions:
      contents: read # Needed to clone the repo.
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-deploy-assets.yml@135418d4eb310ba1d62222d0be6c3d6952dfde01 # 2.2.0
    with:
      plugin: user-switching
      readme: readme.txt
      username: johnbillion
    secrets:
      WPORG_SVN_PASSWORD: ${{ secrets.WPORG_SVN_PASSWORD }}
