# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: FAIR testing
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: The version number of the release

concurrency: FAIR testing

permissions: {}

jobs:
  deploy:
    name: Deploy Tag
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-fair-metadata.yml@fair-tooling
    permissions:
      contents: write        # Required to push the new branch
      pull-requests: write   # Required to create the pull request
    with:
      plugin: user-switching
      did: did:plc:ap4bi3w5w42oy7hfom57tehj
      fair-path: fair.json
      version: ${{ github.event.inputs.version }}
    secrets:
      FAIR_VERIFICATION_KEY: ${{ secrets.FAIR_VERIFICATION_KEY }}
