# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Integration Tests
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
    paths:
      - '.github/workflows/integration-tests.yml'
      - 'tests/integration/**'
      - 'user-switching.php'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'docker-compose.yml'
      - 'package.json'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/integration-tests.yml'
      - 'tests/integration/**'
      - 'user-switching.php'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'docker-compose.yml'
      - 'package.json'
  workflow_dispatch:

permissions: {}

jobs:
  test:
    name: WP ${{ matrix.wp }}
    permissions:
      contents: read # Needed to clone the repo.
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-integration-tests.yml@99fbf371962704dbaef452ebe7ea188d5cfb8069 # 2.9.4
    strategy:
      # See the following for PHP compatibility of WordPress versions:
      # https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/
      matrix:
        wp:
          # Three most recent versions of WordPress:
          - '7.0'
          - '6.9'
          - '6.8'
        php:
          # Most recent version of PHP supported by all of the above:
          - '8.4'
          # Oldest support PHP:
          - '7.4'
        include:
          # Latest WordPress on latest PHP:
          - wp: '7.0'
            php: '8.5'
          # Oldest supported WordPress on its newest supported PHP:
          - wp: '6.2'
            php: '8.2'
          # Oldest supported WordPress on oldest support PHP:
          - wp: '6.2'
            php: '7.4'
      fail-fast: false
    with:
      php: ${{ matrix.php }}
      wp: ${{ matrix.wp }}
